name: movies_redux
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  auto_route: ^7.2.0
  cloud_firestore: ^4.6.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_database: ^10.2.0
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter:
  assets:
    - assets/

  uses-material-design: true
